apiVersion: v1
kind: Service
metadata:
  labels:
    app: config-service
  name: bootu-config
spec:
  ports:
  - port: 8801
    protocol: TCP
    targetPort: 8080
  selector:
    app: config-service
  type: ClusterIP
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: bootu-config-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: config-service
    spec:
      containers:
      - name: bootu-config
        image: orionhank/bootu-config:latest
        ports:
        - containerPort: 8080

